### ISSUE TITLE
`get_task_data()` not working

### ISSUE THREAD

**Issue by ries9112** [itzmestar/Octoparse#5]
When I use `get_task_data()` for whatever reason the code gets totally stuck and just never stops running, even if I set a size of 1, which should be instant. Not having this problem with any of the other functions. I can provide more details about my configuration, but I would be curious to hear if everything works as expected on your end and if anything in particular would be helpful in troubleshooting.

Thank you!

**Comment by itzmestar** [comment]
hi @ries9112 : size argument is the 'chunk size to be fetched in each request'. so setting it to 1 means that 1 data row will be fetched at a time. 
get_task_data() will return all the data rows for the task starting from the offset.

it is probably trying to fetch all the data & it may look like its stuck.

Please share any other details. thanks

**Comment by itzmestar** [comment]
hi @ries9112,
i have implemented 2 new methods you might be interested in. please see the new release. thanks

**Comment by ries9112** [comment]
I just read through the new `get_data_by_offset()` function and it's awesome, thank you for adding it in! Also very nice additions to the docstring for `get_task_data()`, thanks for a great package and great new function! Haven't had a chance to test this yet, but will let you know if I run into unexpected problems.
